version: '3' #versão do docker-compose
services: #servicõs a serem adicionados neste container devem ficar logo abaixo
  postgres:
    image: postgres:latest #imagem e versão
    container_name: devstore #nome do container
    environment: #definições de ambiente devem ficar aqui abaixo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devstore_api
    ports:
      - "5434:5432" # porta_da_maquina_fisica : porta_do_container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data