ALTER TABLE users ALTER COLUMN enabled DROP DEFAULT;
ALTER TABLE users ALTER COLUMN enabled TYPE BOOLEAN USING CASE WHEN enabled=0 THEN FALSE ELSE TRUE END;
ALTER TABLE users ALTER COLUMN enabled SET DEFAULT FALSE;