ALTER TABLE product ADD featured SMALLINT;
ALTER TABLE product ALTER COLUMN featured DROP DEFAULT;
ALTER TABLE product ALTER COLUMN featured TYPE BOOLEAN USING CASE WHEN featured=0 THEN FALSE ELSE TRUE END;
ALTER TABLE product ALTER COLUMN featured SET DEFAULT FALSE;